export default {
  setup: "Setup & Provider",
  "client-proxy": "Client Proxy SDK",
  "ssr-hydration": "SSR Hydration & Persistence",
  batching: "Request Batching & Deduplication",
  devtools: "Actyx DevTools",
  queries: "Queries & Parallel Fetching",
  "infinite-queries": "Infinite Queries",
  "paginated-queries": "Paginated Queries",
  mutations: "Mutations & File Uploads",
  "cache-mutations": "Cache Mutations & Rollbacks",
  subscriptions: "WebSocket Subscriptions",
  sse: "Server-Sent Events (SSE)",
  "real-time-infinite-queries": "Real-Time Infinite Queries",
  utilities: "React Utilities",
};
